//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Visualizations.ProjectM.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create multiple ProjectM instances, it is unstable..
        /// </summary>
        internal static string ProjectM_InstanceWarning {
            get {
                return ResourceManager.GetString("ProjectM.InstanceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project M.
        /// </summary>
        internal static string ProjectM_Name {
            get {
                return ResourceManager.GetString("ProjectM.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ProjectM_Next {
            get {
                return ResourceManager.GetString("ProjectM.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string ProjectM_Pause {
            get {
                return ResourceManager.GetString("ProjectM.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string ProjectM_Previous {
            get {
                return ResourceManager.GetString("ProjectM.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ProjectM_Search {
            get {
                return ResourceManager.GetString("ProjectM.Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create OpenGL context while transparency is enabled, please disable it and restart..
        /// </summary>
        internal static string ProjectM_TransparencyWarning {
            get {
                return ResourceManager.GetString("ProjectM.TransparencyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Complexity_Extreme {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Complexity.Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Complexity_High {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Complexity.High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Complexity_Low {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Complexity.Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Complexity_Medium {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Complexity.Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (Seconds).
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Interval {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project M.
        /// </summary>
        internal static string ProjectMBehaviourConfiguration_Section {
            get {
                return ResourceManager.GetString("ProjectMBehaviourConfiguration.Section", resourceCulture);
            }
        }
    }
}
