//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.UI.Windows.Dialogs.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string ToolWindowBehaviour_Manage {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ToolWindowBehaviour_New {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string ToolWindowBehaviour_NewWindow {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        internal static string ToolWindowBehaviour_Path {
            get {
                return ResourceManager.GetString("ToolWindowBehaviour.Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        internal static string ToolWindowKeyBindingsBehaviourConfiguration_Manage {
            get {
                return ResourceManager.GetString("ToolWindowKeyBindingsBehaviourConfiguration.Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        internal static string ToolWindowManager_AlwaysOnTop {
            get {
                return ResourceManager.GetString("ToolWindowManager.AlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component.
        /// </summary>
        internal static string ToolWindowManager_Component {
            get {
                return ResourceManager.GetString("ToolWindowManager.Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Main.
        /// </summary>
        internal static string ToolWindowManager_CopyToMain {
            get {
                return ResourceManager.GetString("ToolWindowManager.CopyToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Layout XML.
        /// </summary>
        internal static string ToolWindowManager_EditLayoutXML {
            get {
                return ResourceManager.GetString("ToolWindowManager.EditLayoutXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Main Window.
        /// </summary>
        internal static string ToolWindowManager_MainWindow {
            get {
                return ResourceManager.GetString("ToolWindowManager.MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show With Mini Window.
        /// </summary>
        internal static string ToolWindowManager_MiniWindow {
            get {
                return ResourceManager.GetString("ToolWindowManager.MiniWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ToolWindowManager_Title {
            get {
                return ResourceManager.GetString("ToolWindowManager.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog Manager.
        /// </summary>
        internal static string ToolWindowManagerWindow_Title {
            get {
                return ResourceManager.GetString("ToolWindowManagerWindow.Title", resourceCulture);
            }
        }
    }
}
