//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxTunes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxTunes.DB.SQLite.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [Main](
        ///	[Checksum] text COLLATE NOCASE);
        ///
        ///CREATE TABLE [MetaDataItems](
        ///	[Id] INTEGER PRIMARY KEY NOT NULL, 
        ///	[Name] text NOT NULL COLLATE NOCASE, 
        ///	[Type] bigint NOT NULL,
        ///	[Value] text COLLATE NOCASE);
        ///
        ///CREATE TABLE [LibraryRoots] (
        ///	[Id] INTEGER PRIMARY KEY NOT NULL, 
        ///	[DirectoryName] text NOT NULL COLLATE NOCASE);
        ///
        ///CREATE TABLE [LibraryItems] (
        ///	[Id] INTEGER PRIMARY KEY NOT NULL, 
        ///	[DirectoryName] text NOT NULL COLLATE NOCASE, 
        ///	[FileName] text NOT NULL COLLATE NOCASE, 
        ///	[ImportDate] text [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH &quot;MetaData&quot;
        ///AS (
        ///    SELECT 
        ///        &quot;LibraryItems&quot;.&quot;FileName&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @artist THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Artist&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @album THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Album&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @track THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Track&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @title THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Title&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataIte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetEntireLibrary {
            get {
                return ResourceManager.GetString("GetEntireLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH &quot;MetaData&quot; AS (
        ///    SELECT 
        ///        &quot;LibraryItems&quot;.&quot;FileName&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @artist THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Artist&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @album THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Album&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @title THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;Title&quot;,
        ///        MAX(CASE WHEN &quot;MetaDataItems&quot;.&quot;Name&quot; = @lastPlayed THEN &quot;MetaDataItems&quot;.&quot;Value&quot; END) AS &quot;LastPlayed&quot;,
        ///        SUM(CASE WHEN &quot;MetaDataI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetListeningHistory {
            get {
                return ResourceManager.GetString("GetListeningHistory", resourceCulture);
            }
        }
    }
}
